### ISSUE TITLE
Mendeley isn't aware of Libreoffice and doesn't show option for Libreoffice plugin

### ISSUE THREAD

**Issue by brittyazel** [flathub/com.elsevier.MendeleyDesktop#11]
Mendeley when installed as a flatpak doesn't show the option to install the libreoffice plugin. It doesn't matter if Libreoffice is installed as a flatpak or native (ArchLinux), neither show within Mendeley.

I'm not sure what permissions or access Mendeley needs to have the libreoffice plugin work, but it's pretty imperative that this feature be fixed, because that's like 50% of Mendeley's usecase for me.

**Comment by nedrichards** [comment]
If you run on the command line with --filesystem=host does anything change? (it may not)

**Comment by Erick555** [comment]
@brittyazel you can try installing mendeley plugin manually in LO. The plugin in system-wide installation is available here: `/var/lib/flatpak/app/com.elsevier.MendeleyDesktop/current/active/files/extra/share/mendeleydesktop/openOfficePlugin/Mendeley-1.19.2.oxt`. You may copy it to some shared dir and install through LO plugin manager. User reported it worked for him with[ zotero plugin](https://github.com/flathub/org.libreoffice.LibreOffice/issues/7).

**Comment by brittyazel** [comment]
yeah that worked. Sorry for the long delay!

It's a working solution, albeit a messy one. Thanks for the suggestion!
