### ISSUE TITLE
Problems with GL

### ISSUE THREAD

**Issue by jonasbb** [flathub/com.elsevier.MendeleyDesktop#28]
I have troubles running Mendeley 1.19.5 with flatpak.

I see the following messages on the terminal: 
```shell
$ flatpak run com.elsevier.MendeleyDesktop
Gtk-Message: 12:30:07.805: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:30:07.805: Failed to load module "pk-gtk-module"
Gtk-Message: 12:30:07.806: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:30:07.806: Failed to load module "pk-gtk-module"
Could not initialize GLX
```

Flatpak does not have any GL module installed.
If I run `flatpak update` it installs `org.freedesktop.Platform.GL.default` from the 19.08 branch. However, as soon as I run `flatpak uninstall --unused` the `org.freedesktop.Platform.GL.default` will be uninstalled again.

This flatpak should have a proper dependency on the GL stuff and not be detected as unused.

**Comment by Erick555** [comment]
This is [known bug in flatpak](https://github.com/flatpak/flatpak/issues/3004) which occurs with apps that use 19.08 runtime. You have to update to flatpak 1.4.3 or don't use `flatpak uninstall --unused`
