### ISSUE TITLE
QT 5.10 needed  with 1.18

### ISSUE THREAD

**Issue by Erick555** [flathub/com.elsevier.MendeleyDesktop#3]
New version needs qt 5.10 libs:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mendeleydesktop --file-forwarding com.elsevier.MendeleyDesktop         
/app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64: /usr/lib/libQt5Core.so.5: version `Qt_5.10' not found (required by /app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64)
/app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64: /usr/lib/libQt5Core.so.5: version `Qt_5.10' not found (required by /app/extra/lib/libMendeley.so.1.18)
```

I would make PR but I don't know if I need to update kde runtime or kde sdk or both.

**Comment by nedrichards** [comment]
You need to change this line to say "5.10" https://github.com/flathub/com.elsevier.MendeleyDesktop/blob/master/com.elsevier.MendeleyDesktop.json#L4

**Comment by Erick555** [comment]
@nedrichards thx, done https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/4

**Comment by brittyazel** [comment]
I too have this issue, I can't get Mendeley to open without complains for Qt 5.10

**Comment by Erick555** [comment]
It still crashes with:
```
/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mendeleydesktop --file-forwarding com.elsevier.MendeleyDesktop          
/app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64: relocation error: /app/extra/lib/mendeleydesktop/plugins/bearer/libqconnmanbearer.so: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference
```
It works fine installed natively on Archlinux.

**Comment by brittyazel** [comment]
I also get:
`Failed to run mendeley:// link handler installer "/app/extra/lib/mendeleydesktop/libexec/install-mendeley link-handler.sh" /app/extra/lib/mendeleydesktop/libexec/mendeleydesktop.x86_64: relocation error: /app/extra/lib/mendeleydesktop/plugins/bearer/libqconnmanbearer.so: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference`
