### ISSUE TITLE
Crash on startup after update.

### ISSUE THREAD

**Issue by emil-varga** [flathub/com.elsevier.MendeleyDesktop#36]
Hello,

after update on Saturday, May 16, 2020 Mendeley crashes on start on my system. Version 1.19.4 downloaded from Elsevier (64bit generic linux version) runs fine. My OS is Fedora 32 workstation edition, flatpak version 1.6.3

Output of $flatpak run com.elsevier.MendeleyDesktop
[mendeley_run.txt](https://github.com/flathub/com.elsevier.MendeleyDesktop/files/4641634/mendeley_run.txt)

And $flatpak info com.elsevier.MendeleyDesktop
[mendeley_info.txt](https://github.com/flathub/com.elsevier.MendeleyDesktop/files/4641637/mendeley_info.txt)

**Comment by Erick555** [comment]
Your are right, they downgraded version to from 1.19.6 1.19.4 in apt repo again and it seems something in mendeley config isn't backward compatible and crash. I'll update to 1.19.6 again. Sorry for inconvenience.
