### ISSUE TITLE
Searching all entries that have associated notes

### ISSUE THREAD

**Issue by iburunat** [flathub/com.elsevier.MendeleyDesktop#38]
I have a question pertaining `notes`. I wonder if there is a way to find all citation entries that contain `notes`. This I believe would be useful to extract all entries associated with notes. This is not a search for content in the "`note`" field. This is merely a search of all entries that have `notes` to them. Thanks in advance!

**Comment by Erick555** [comment]
Hi, this repo is for flatpak packaging issues, for general support for this app you may ask in this place https://service.elsevier.com/app/social/home/supporthub/mendeley/

**Comment by iburunat** [comment]
Thanks and apologies!
