### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by gwnichol** [flathub/com.elsevier.MendeleyDesktop#43]
Hello, I've tried installing with `--user` and without and I've run into the same error each time:
```
> flatpak --user install flathub com.elsevier.MendeleyDesktop         
Looking for matches…

com.elsevier.MendeleyDesktop permissions:
    ipc    network    x11    dri    file access [1]    dbus access [2]    tags [3]

    [1] /tmp, home
    [2] org.freedesktop.Notifications, org.kde.StatusNotifierWatcher
    [3] proprietary


        ID                                     Branch           Op          Remote           Download
 1. [/] com.elsevier.MendeleyDesktop           stable           i           flathub          124.4 MB / 125.0 MB

Installing… ████████████████████ 100%  62.2 MB/sar: error while loading shared libraries: libbfd-2.35.1.so: cannot open shared object file: No such file or directory
tar: data.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'opt/mendeleydesktop/*': No such file or directory
sed: can't read share/applications/mendeleydesktop.desktop: No such file or directory
install: cannot stat 'share/icons/hicolor/16x16/apps/mendeleydesktop.png': No such file or directory
install: cannot stat 'share/icons/hicolor/22x22/apps/mendeleydesktop.png': No such file or directory
install: cannot stat 'share/icons/hicolor/32x32/apps/mendeleydesktop.png': No such file or directory
        ID                                     Branch           Op          Remote           Download
 1. [✗] com.elsevier.MendeleyDesktop           stable           i           flathub          124.4 MB / 125.0 MB

Error: Key file does not start with a group
error: Failed to install com.elsevier.MendeleyDesktop: Key file does not start with a group
```

I've made sure to update any of my other flatpaks before installing this.

I don't work with flatpaks very often so I'm not sure how to debug further than this. I've tried searching online, but was unable to find anything useful. Any help would be greatly appreciated.

**Comment by Erick555** [comment]
It works for me. What distribution is this and what flatpak version? You may check with `flatpak --version`. Could you also show `ls -l /usr/bin/bwrap` command output?

It's possible this is related to old flatpak version or bwrap binary installed in setuid mode. Could you try installing it from https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/44#issuecomment-815682242 ?

**Comment by gwnichol** [comment]
Yes the build from [#44 (comment)](https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/44#issuecomment-815682242) fixed my problem.

I have Flatpak 1.10.0, and /usr/bin/bwrap does have the setuid mode set.

**Comment by Erick555** [comment]
@gwnichol interesting, I don't know what may be the cause then, does executing `echo $LD_LIBRARY_PATH`  on host terminal shows any output?

**Comment by gwnichol** [comment]
Nope. That variable isn't set. My libbfd is at `/usr/lib64/libbfd-2.35.1.gentoo-sys-libs-binutils-libs-st-def.so`. `/usr/lib64/libbfd.so` links there. Not sure why that would effect the flatpak.

**Comment by Erick555** [comment]
The thing is libbfd is part of flatpak app, you may find it under `lib` folder among app files and  in `/app/lib` in sandbox. libbfd from host shouldn't have any matter. It's a mystery to me why it doesn't work for some users.
