### ISSUE TITLE
Mendeley Desktop on a Raspberry Pi 4

### ISSUE THREAD

**Issue by DuchenneSmile** [flathub/com.elsevier.MendeleyDesktop#46]
Greetings, 
I'm trying to install Mendeley Desktop via Flatpak on a Raspberry Pi 4 (aarch64) on Manjaro.

But when I tried to install it, here is the issue:
`Nothing matches com.elsevier.MendeleyDesktop in remote flathub`

I don't know if it would be possible to enable this flatpak for this architecture. I tried to install it via the tarball on the Mendeley website but can't succeed despite many attempts.

Thanks a lot for what you could do, I don't know if enabling this architecture is possible/easy.

**Comment by Erick555** [comment]
Upstream doesn't support arm/aarch64 architecture so it's not possible to get it from any channel.

**Comment by DuchenneSmile** [comment]
Thanks for this as quick answer !
