### ISSUE TITLE
Creates desktop file with invalid binary location

### ISSUE THREAD

**Issue by TuxCoding** [flathub/com.elsevier.MendeleyDesktop#48]
On startup Mendeley always creates a `.desktop` in `.local/share/applications` in order to install for the link handler, but binary file is set to `.local/share/mendeleydesktop` which doesn't exist in case of flatpak.

**Comment by Erick555** [comment]
I guess we can prevent mendeley from creating the .desktop file as we already have it in flatpak. Thx for the report.
