### ISSUE TITLE
Application hangs on exit with the newest runtime.

### ISSUE THREAD

**Issue by TuxCoding** [flathub/com.elsevier.MendeleyDesktop#51]
The newest runtime dump lets Mendeley hang on exit. It doesn't completely close, but consume 100% usage on a single core. I have to kill it to end it.

My system is openSUSE Tumbleweed. Maybe they depend on a certain library version.

**Comment by Erick555** [comment]
I prepared revert to the old runtime in https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/52 Please confirm if this problem doesn't occur there.

Mendeley doesn't directly depend on runtime libraries so it's hard to tell what exact causes this problem.

**Comment by TuxCoding** [comment]
Yes that fixes it
