### ISSUE TITLE
Modules not loaded despite their presence in the system is attested

### ISSUE THREAD

**Issue by Ricky-Tigg** [flathub/com.elsevier.MendeleyDesktop#54]
OS: Fedora.
```
$ locate /usr/lib64/ *canberra-gtk*-module.so
/usr/lib64/gtk-2.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so
/usr/lib64/gtk-3.0/modules/libcanberra-gtk3-module.so
$ locate /usr/lib64/ *pk-gtk*-module.so
/usr/lib64/gtk-3.0/modules/libpk-gtk-module.so
$ rpm -qf /usr/lib64/gtk-3.0/modules/libcanberra-gtk-module.so
libcanberra-gtk3-0.30-31.fc38.x86_64
$ rpm -qf /usr/lib64/gtk-3.0/modules/libpk-gtk-module.so
PackageKit-gtk3-module-1.2.6-6.fc38.x86_64
$ flatpak --runtime --columns=name,application,version,branch list | grep '^Freedesktop Platform'
Freedesktop Platform	org.freedesktop.Platform	21.08.18	21.08
Freedesktop Platform	org.freedesktop.Platform	22.08.12.1	22.08
$ flatpak --app-runtime=org.freedesktop.Platform --columns=name,version,runtime list
Name              Version          Runtime
Mendeley          1.19.8           org.freedesktop.Platform/x86_64/21.08
```
Hello. Modules not loaded despite their presence in the system is attested.

Note: Workaround to the non-updated runtime. same output with the original runtime version. Application launched successfully with this output:
```
$ flatpak --runtime-version=22.08 run com.elsevier.MendeleyDesktop
Gtk-Message: 19:30:20.711: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:30:20.711: Failed to load module "pk-gtk-module"
Failed to run mendeley:// link handler installer "/app/extra/bin/install-mendeley-link-handler.sh"
```

**Comment by Erick555** [comment]
Those modules aren't present inside flatpak and this cause above warning. As the workaroud you may run `flatpak override --user --env=GTK_MODULES=`.

**Comment by Ricky-Tigg** [comment]
```
$ flatpak info com.elsevier.MendeleyDesktop | awk 'NF' | sed -n 10p
Installation: system
```
Then that puts me in position having to execute commands with elevated privilege.
```
$ sudo flatpak override --env=GTK_MODULES=
$ sudo -i
# flatpak run com.elsevier.MendeleyDesktop
Failed to run mendeley:// link handler installer "/app/extra/bin/install-mendeley-link-handler.sh"
```

**Comment by Erick555** [comment]
> Then that puts me in position having to execute commands with elevated privilege.

I proposed to run `flatpak override --user --env=GTK_MODULES=` which doesn't require elevated privileges and work for both system and user flatpak installations. it was your choice to not follow it.

Either way as you see the problem is solved.

**Comment by Ricky-Tigg** [comment]
What made you believe one moment that you could even know that? Behind your screen; a special one? Wake up! That's precisely by following **your** very suggestion, which had produced nothing else than
```
$ flatpak override --user --env=GTK_MODULES=
$ flatpak run com.elsevier.MendeleyDesktop
Gtk-Message: 18:28:21.539: Failed to load module "canberra-gtk-module"
Gtk-Message: 18:28:21.539: Failed to load module "pk-gtk-module"
Failed to run mendeley:// link handler installer "/app/extra/bin/install-mendeley-link-handler.sh"
```
, which obviously spoke for itself, that i had to investigate. Closing was indeed the thing to do when like here it does appear that we have had a wrong person for the right task. My choice here, **if any**, was no more to have picked up the present application. That, if it could be a problem, won't be anymore. No more time to waste.

**Comment by Erick555** [comment]
The system override you made has exact same effect as user override and I thought it fixed your problem because you showed there is no warning anymore. 

However in your example you simply run whole flatpak app as root which is totally unsupported and accidentally fixed gtk warning which is just a cosmetic issue and isn't related in any way to mendeley flatpak (it doesn't use gtk).

I've never asked and never will ask you to run anything with elevated privs. 

You need to find what in your system environment calls for those modules and fix it or ignore it since it doesn't have any consequences.
