### ISSUE TITLE
"Open file" and "open containing folder" is not working

### ISSUE THREAD

**Issue by ghost** [flathub/com.elsevier.MendeleyDesktop#7]
Dear developers,

if I'm in the details tab of an literature entry the commands "open file" and "open containing folder" do not do anything.

My flatpak version is 0.8.8.
The mendeley version is: 
```app/com.elsevier.MendeleyDesktop/x86_64/stable flathub 07ac8a6324cc684f86bba8e4f37ca67c652dfecf5ca5f545262829995023d96f```

Regards

**Comment by Erick555** [comment]
I tested this with flatpak 1.0 and Mendeley 1.19.2 in KDE and "open file", "open file externally" and "open containing folder" works correctly for me.

**Comment by ghost** [comment]
Well, I'm using CentOS with a older flatpak version (0.8.8). This might be the reason as I (with my old flatpak version) had some issues with the texwriter package that newer flatpak versions did not have.

So I'll close the bug report then.
