### ISSUE TITLE
Add a screenshot on Linux

### ISSUE THREAD

**Issue by dsboger-zz** [flathub/com.elsevier.MendeleyDesktop#8]
It is weird for a Linux app store to show a screenshot on MacOS :). Maybe you could "host" it in the downstream repo?

Thanks!

**Comment by nedrichards** [comment]
Contributions welcome! Hosting assets in the repo is what a lot of other apps do, that'd work fine.

**Comment by cho2** [comment]
@nedrichards ~~https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/20~~ https://github.com/flathub/com.elsevier.MendeleyDesktop/pull/21

**Comment by Erick555** [comment]
@cho2 thx for your help!

**Comment by cho2** [comment]
@Erick555 my pleasure
