### ISSUE TITLE
New Mendeley version 1.19.1

### ISSUE THREAD

**Issue by ghost** [flathub/com.elsevier.MendeleyDesktop#9]
Hi there,

I just saw that a new Mendeley version is available.
[Mendeley 1.19.1 x86_64](https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.19.1-linux-x86_64.tar.bz2)
[Mendeley 1.19.1 i486](https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.19.1-linux-i486.tar.bz2)

md5sum (x86_64) : ```f6f186cba357cfe1db4d863a50af60a2```
md5sum (i486): ```30dfad68f0ab0a56e54a992ef6f0361c```

Could you update the mendeley package with the new version?

Regards,

Jakob

**Comment by nedrichards** [comment]
Fixed by https://github.com/flathub/com.elsevier.MendeleyDesktop/commit/3dc9fcc5603ab1ffc944bbdb0d9c0f7cf7aa7758
